os: linux
language: node_js

node_js:
  - '10'
  - node
  - lts/*

branches:
  only:
    - master
    - beta
    - next

install: travis_retry yarn install

script:
  - npm test
  - npm run coveralls

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npx semantic-release
